export const ru = {
  'app.name': 'OneCart',
  'app.logoLabel': 'Логотип OneCart',

  'nav.home': 'Главная',
  'nav.stores': 'Магазины',
  'nav.add': 'Добавить',
  'nav.history': 'История',
  'nav.profile': 'Профиль',
  'nav.mainLabel': 'Основная навигация',

  'common.back': 'Назад',
  'common.close': 'Закрыть',
  'common.cancel': 'Отмена',
  'common.save': 'Сохранить',
  'common.done': 'Готово',
  'common.continue': 'Продолжить',
  'common.start': 'Начать',
  'common.add': 'Добавить',
  'common.create': 'Создать',
  'common.edit': 'Изменить',
  'common.delete': 'Удалить',
  'common.remove': 'Убрать',
  'common.rename': 'Переименовать',
  'common.open': 'Открыть',
  'common.confirm': 'Подтвердить',
  'common.retry': 'Повторить',
  'common.undo': 'Отменить',
  'common.search': 'Поиск',
  'common.clear': 'Очистить',
  'common.apply': 'Применить',
  'common.select': 'Выбрать',
  'common.selected': 'Выбрано: {{count}}',
  'common.more': 'Ещё',
  'common.share': 'Поделиться',
  'common.invite': 'Пригласить',
  'common.move': 'Переместить',
  'common.pin': 'Закрепить',
  'common.unpin': 'Открепить',
  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.optional': 'Необязательно',
  'common.required': 'Обязательно',
  'common.enabled': 'Включено',
  'common.disabled': 'Отключено',
  'common.notSpecified': 'Не указано',
  'common.notAvailable': 'Недоступно',
  'common.productsCount': 'Товаров: {{count}}',
  'common.purchasedProgress': 'Куплено: {{purchased}} из {{total}}',
  'common.approximate': 'Ориентировочно',
  'common.currencyUah': 'Гривна (₴)',

  'a11y.pageIndicator': 'Шаг {{current}} из {{total}}',
  'a11y.skipToContent': 'Перейти к содержимому',
  'a11y.openNotifications': 'Открыть уведомления',
  'a11y.openProfile': 'Открыть профиль',
  'a11y.openMoreMenu': 'Открыть дополнительное меню',
  'a11y.closeSheet': 'Закрыть нижнее меню',
  'a11y.openStoreList': 'Открыть список магазина {{store}}',
  'a11y.markPurchased': 'Отметить {{product}} купленным',
  'a11y.markNotPurchased': 'Вернуть {{product}} в список покупок',
  'a11y.expandCategory': 'Развернуть категорию {{category}}',
  'a11y.collapseCategory': 'Свернуть категорию {{category}}',
  'a11y.progress': 'Куплено {{purchased}} из {{total}} товаров',
  'a11y.decreaseQuantity': 'Уменьшить количество',
  'a11y.increaseQuantity': 'Увеличить количество',

  'splash.title': 'OneCart',

  'onboarding.first.title': 'Все покупки в одном месте',
  'onboarding.first.description':
    'Создавайте списки для любых магазинов и управляйте ими из одного приложения.',
  'onboarding.second.title': 'Покупайте вместе',
  'onboarding.second.description':
    'Делитесь списком с семьёй и сразу видьте изменения.',
  'onboarding.third.title': 'Ничего не забудьте',
  'onboarding.third.description':
    'Добавляйте товары вручную, голосом или из истории покупок.',
  'onboarding.continue': 'Продолжить',
  'onboarding.start': 'Начать',

  'home.greeting': 'Здравствуйте',
  'home.title': 'Мои покупки',
  'home.generalList': 'Общий список',
  'home.openGeneralList': 'Открыть общий список',
  'home.storeLists': 'Списки по магазинам',
  'home.frequentProducts': 'Часто покупаете',
  'home.chooseDestination': 'Выберите список для товара',
  'home.addedToList': '{{product}} добавлен в {{list}}',
  'home.allPurchased': 'Все товары куплены',
  'home.noActivePurchases': 'Активных покупок пока нет',

  'quickActions.title': 'Что добавить?',
  'quickActions.product': 'Добавить товар',
  'quickActions.list': 'Создать список',
  'quickActions.store': 'Добавить магазин',
  'quickActions.voice': 'Добавить товар голосом',

  'stores.title': 'Магазины',
  'stores.add': 'Добавить магазин',
  'stores.openList': 'Открыть список',
  'stores.status': 'Статус списка',
  'stores.status.active': 'Активный',
  'stores.status.completed': 'Завершён',
  'stores.status.empty': 'Пустой',
  'stores.menu.rename': 'Переименовать',
  'stores.menu.changeLocation': 'Изменить местоположение',
  'stores.menu.changeColor': 'Изменить цвет',
  'stores.menu.pin': 'Закрепить',
  'stores.menu.unpin': 'Открепить',
  'stores.menu.openOfficialApp': 'Открыть официальное приложение',
  'stores.menu.delete': 'Удалить из OneCart',
  'stores.externalAppUnavailable': 'Ссылка на официальное приложение не добавлена.',
  'stores.customBadge': 'Свой магазин',
  'stores.location.notSpecified': 'Местоположение не указано',

  'storeCatalog.title': 'Каталог магазинов',
  'storeCatalog.searchLabel': 'Найти магазин',
  'storeCatalog.searchPlaceholder': 'Название магазина',
  'storeCatalog.popular': 'Популярные магазины',
  'storeCatalog.other': 'Другой магазин',
  'storeCatalog.configure': 'Настроить',
  'storeCatalog.addStandard': 'Добавить магазин',
  'storeCatalog.setupTitle': 'Настройка {{store}}',
  'storeCatalog.setupDescription': 'Укажите филиал, параметры списка и ссылку сети.',
  'storeCatalog.favoriteBranch': 'Любимый филиал или адрес',
  'storeCatalog.branchHint': 'Укажите адрес или название филиала. Это необязательно.',
  'storeCatalog.includeInGeneral': 'Включить в общий список',
  'storeCatalog.includeInGeneralHint':
    'Создать активный список магазина и показывать его товары в общем списке.',
  'storeCatalog.externalAppUrl': 'Ссылка на сайт или каталог',
  'storeCatalog.externalAppUrlHint':
    'Используется для действия «Открыть официальное приложение».',
  'storeCatalog.noResults': 'Магазины не найдены',
  'storeCatalog.noResultsHint': 'Проверьте название или добавьте свой магазин.',
  'storeForm.createTitle': 'Новый магазин',
  'storeForm.editTitle': 'Изменить магазин',
  'storeForm.name': 'Название',
  'storeForm.namePlaceholder': 'Например, Магазин у дома',
  'storeForm.color': 'Цвет',
  'storeForm.icon': 'Иконка',
  'storeForm.city': 'Город',
  'storeForm.cityPlaceholder': 'Выберите или введите город',
  'storeForm.address': 'Адрес',
  'storeForm.addressPlaceholder': 'Улица, дом или название филиала',
  'storeForm.useCurrentLocation': 'Использовать моё местоположение',
  'storeForm.locating': 'Определяем местоположение…',
  'storeForm.locationReady': 'Координаты сохранены и будут показаны вместе с адресом.',
  'storeForm.locationUnsupported': 'Геолокация не поддерживается на этом устройстве.',
  'storeForm.locationDenied': 'Не удалось получить геолокацию. Проверьте разрешение приложения.',
  'storeForm.coordinates': 'Координаты',
  'storeForm.branch': 'Филиал',
  'storeForm.saveUrl': 'Сохранить ссылку на приложение',

  'lists.generalTitle': 'Общий список покупок',
  'lists.unassigned': 'Не распределено',
  'lists.distributed': 'Распределено по магазинам',
  'lists.remaining': 'Осталось купить',
  'lists.purchased': 'Куплено',
  'lists.addProduct': 'Добавить товар',
  'lists.create': 'Создать список',
  'lists.createTitle': 'Новый список',
  'lists.activeExists': 'Для этого раздела уже есть активный список. Его можно открыть без создания дубля.',
  'lists.editTitle': 'Изменить список',
  'lists.name': 'Название списка',
  'lists.store': 'Магазин',
  'lists.noStore': 'Без магазина',
  'lists.purchaseMode': 'Режим покупки',
  'lists.bulkDistribution': 'Распределить товары',
  'lists.completePurchase': 'Завершить покупку',
  'lists.completeUnavailable': 'Сначала отметьте все товары купленными.',
  'lists.itemsRemaining': 'Осталось: {{count}}',
  'lists.categoryCount': 'В категории: {{count}}',
  'lists.expandCategory': 'Показать товары',
  'lists.collapseCategory': 'Скрыть товары',
  'lists.sharedAccess': 'Совместный доступ',
  'lists.updatedAt': 'Обновлено {{date}}',
  'lists.addedBy': 'Добавил {{name}}',

  'products.addTitle': 'Добавить товар',
  'products.editTitle': 'Изменить товар',
  'products.detailsTitle': 'Карточка товара',
  'products.name': 'Название',
  'products.namePlaceholder': 'Что нужно купить?',
  'products.quantity': 'Количество',
  'products.unit': 'Единица измерения',
  'products.store': 'Магазин',
  'products.category': 'Категория',
  'products.estimatedPrice': 'Ориентировочная цена',
  'products.priceHint': 'Цена указана приблизительно',
  'products.photo': 'Фото товара',
  'products.photoAlt': 'Фото товара {{product}}',
  'products.photoSource': 'Официальный источник: {{source}}',
  'products.note': 'Заметка',
  'products.notePlaceholder': 'Например, без сахара',
  'products.mode.manual': 'Вручную',
  'products.mode.voice': 'Голосом',
  'products.mode.scanner': 'Сканером',
  'products.suggestions': 'Подсказки из истории',
  'products.markPurchased': 'Отметить купленным',
  'products.markNotPurchased': 'Вернуть в покупки',
  'products.changeQuantity': 'Изменить количество',
  'products.changeStore': 'Сменить магазин',
  'products.addNote': 'Добавить заметку',
  'products.addToFrequent': 'Добавить в часто покупаемые',
  'products.removeFromFrequent': 'Убрать из часто покупаемых',
  'products.delete': 'Удалить товар',
  'products.addedAt': 'Добавлено {{date}}',
  'products.addedBy': 'Добавил {{name}}',
  'products.purchasedAt': 'Куплено {{date}}',
  'products.swipeDelete': 'Смахните влево, чтобы удалить',
  'products.swipePurchase': 'Смахните вправо, чтобы отметить купленным',

  'units.piece': 'шт',
  'units.kg': 'кг',
  'units.g': 'г',
  'units.l': 'л',
  'units.ml': 'мл',
  'units.pack': 'упаковка',

  'categories.produce': 'Овощи и фрукты',
  'categories.dairy': 'Молочные продукты',
  'categories.meat': 'Мясо',
  'categories.drinks': 'Напитки',
  'categories.household': 'Бытовые товары',
  'categories.other': 'Другое',

  'moveProduct.title': 'Переместить товар',
  'moveProduct.currentStore': 'Текущий магазин',
  'moveProduct.destination': 'Куда переместить',
  'moveProduct.unassigned': 'Не распределено',
  'moveProduct.confirm': 'Переместить',
  'moveProduct.sameStore': 'Выберите другой магазин.',
  'moveProduct.success': 'Товар перемещён в {{store}}',

  'distribution.title': 'Распределение товаров',
  'distribution.description': 'Отметьте товары и выберите магазин.',
  'distribution.selectAll': 'Выбрать все',
  'distribution.clearSelection': 'Снять выбор',
  'distribution.chooseStore': 'Выберите магазин',
  'distribution.confirm': 'Распределить',
  'distribution.success': 'Распределено товаров: {{count}}',
  'distribution.dragHint': 'Товары также можно перетаскивать между магазинами.',

  'history.title': 'История покупок',
  'history.purchasesTab': 'Покупки',
  'history.frequentTab': 'Часто покупаемые',
  'history.detailsTitle': 'Покупка',
  'history.total': 'Итоговая сумма',
  'history.date': 'Дата покупки',
  'history.members': 'Участники',
  'history.repeatList': 'Повторить весь список',
  'history.addAgain': 'Добавить снова',
  'history.deleteEntry': 'Удалить запись',
  'history.completedAt': 'Завершено {{date}}',
  'history.repeatDestination': 'Куда добавить товары?',
  'history.repeatSuccess': 'Список добавлен снова',
  'history.entrySummary': '{{store}} · товаров: {{count}}',

  'sharing.title': 'Совместный доступ',
  'sharing.shareStore': 'Поделиться магазином',
  'sharing.shareGeneralList': 'Поделиться общим списком',
  'sharing.shareFamily': 'Поделиться всеми списками семьи',
  'sharing.participants': 'Участники',
  'sharing.invite': 'Пригласить участника',
  'sharing.invitePlaceholder': 'Имя или email',
  'sharing.accessRights': 'Права доступа',
  'sharing.owner': 'Владелец',
  'sharing.editor': 'Редактор',
  'sharing.viewer': 'Только просмотр',
  'sharing.status.active': 'Активен',
  'sharing.status.pending': 'Ожидает приглашения',
  'sharing.removeMember': 'Удалить участника',
  'sharing.simulateChange': 'Сымитировать изменение',
  'sharing.simulatedChange': '{{name}} добавил товар',

  'notifications.title': 'Уведомления',
  'notifications.unreadCount': 'Непрочитано: {{count}}',
  'notifications.markAllRead': 'Отметить все прочитанными',
  'notifications.settings': 'Настройки уведомлений',
  'notifications.mode.all': 'Все изменения',
  'notifications.mode.important': 'Только важные',
  'notifications.muteList': 'Отключить для списка',
  'notifications.productAdded.title': 'Новый товар',
  'notifications.productAdded.message': '{{actor}}: добавлен товар «{{product}}».',
  'notifications.productPurchased.title': 'Товар куплен',
  'notifications.productPurchased.message': '{{actor}}: товар «{{product}}» отмечен купленным.',
  'notifications.listChanged.title': 'Список изменён',
  'notifications.listChanged.message': '{{actor}}: список «{{list}}» изменён.',
  'notifications.memberJoined.title': 'Новый участник',
  'notifications.memberJoined.message': '{{member}} присоединился к списку.',
  'notifications.listCompleted.title': 'Список завершён',
  'notifications.listCompleted.message': 'Покупка в {{store}} завершена.',

  'profile.title': 'Профиль',
  'profile.name': 'Имя',
  'profile.email': 'Email',
  'profile.family': 'Семья',
  'profile.family.members': 'Участники',
  'profile.family.invitations': 'Приглашения',
  'profile.family.permissions': 'Права доступа',
  'profile.application': 'Приложение',
  'profile.data': 'Данные',
  'profile.support': 'Поддержка',

  'settings.title': 'Настройки',
  'settings.notifications': 'Уведомления',
  'settings.language': 'Язык',
  'settings.language.ru': 'Русский',
  'settings.language.uk': 'Українська',
  'settings.currency': 'Валюта',
  'settings.theme': 'Тема',
  'settings.theme.light': 'Светлая',
  'settings.theme.dark': 'Тёмная',
  'settings.theme.system': 'Системная',
  'settings.theme.systemDescription': 'Системная тема автоматически следует настройкам устройства.',
  'settings.units': 'Единицы измерения',
  'settings.defaultUnit': 'Единица по умолчанию',
  'settings.sync': 'Синхронизация',
  'settings.sync.localOnly': 'Данные хранятся только на этом устройстве.',
  'settings.backup': 'Резервная копия',
  'settings.backupDescription': 'Скачать локальную JSON-копию данных',
  'settings.export': 'Экспорт списков',
  'settings.exportDescription': 'Скачать товары и списки в CSV',
  'settings.clearHistory': 'Очистка истории',
  'settings.help': 'Помощь',
  'settings.feedback': 'Обратная связь',
  'settings.about': 'О приложении',
  'settings.aboutDescription': 'OneCart объединяет списки покупок для разных магазинов.',
  'settings.version': 'Версия {{version}}',
  'settings.resetDemo': 'Восстановить демонстрационные данные',

  'empty.lists.title': 'Пока нет списков',
  'empty.lists.description':
    'Создайте первый список и добавьте товары, которые нужно купить.',
  'empty.lists.action': 'Создать список',
  'empty.products.title': 'Список пуст',
  'empty.products.description': 'Добавьте первый товар вручную или голосом.',
  'empty.products.action': 'Добавить товар',
  'empty.history.title': 'Покупок пока нет',
  'empty.history.description': 'Завершённые списки появятся здесь.',
  'empty.stores.title': 'Магазинов пока нет',
  'empty.stores.description': 'Добавьте магазин, чтобы создать для него список.',
  'empty.notifications.title': 'Нет новых уведомлений',
  'empty.notifications.description': 'Изменения в совместных списках появятся здесь.',
  'empty.search.title': 'Ничего не найдено',
  'empty.search.description': 'Попробуйте изменить запрос.',
  'empty.frequent.title': 'Нет часто покупаемых товаров',
  'empty.frequent.description': 'Добавляйте товары, и здесь появятся ваши привычные покупки.',

  'state.loading': 'Загрузка…',
  'state.loadingData': 'Загружаем ваши списки…',
  'state.saving': 'Сохраняем…',
  'state.success': 'Готово',
  'state.offline.title': 'Нет подключения к интернету',
  'state.offline.description': 'Офлайн. Изменения сохранены на устройстве.',
  'state.error.title': 'Что-то пошло не так',
  'state.error.description': 'Не удалось загрузить данные. Попробуйте ещё раз.',
  'state.disabledReason': 'Действие пока недоступно: {{reason}}',
  'state.unsavedChanges': 'Есть несохранённые изменения.',

  'voice.title': 'Добавление голосом',
  'voice.idle': 'Нажмите кнопку и назовите товар.',
  'voice.start': 'Начать запись',
  'voice.stop': 'Остановить запись',
  'voice.listening': 'Слушаю…',
  'voice.transcript': 'Распознанный текст',
  'voice.confirm': 'Добавить этот товар',
  'voice.tryAgain': 'Записать ещё раз',
  'voice.permissionDenied': 'Нет доступа к микрофону.',
  'voice.permissionHint': 'Разрешите доступ или добавьте товар вручную.',
  'voice.mockNotice': 'В прототипе голосовой ввод работает как демонстрация.',
  'voice.simulate': 'Сымитировать распознавание',

  'scanner.title': 'Сканер товара',
  'scanner.instruction': 'Поместите штрихкод в рамку.',
  'scanner.mockNotice': 'Распознавание штрихкода пока работает как демонстрация.',
  'scanner.simulate': 'Сымитировать результат',
  'scanner.manual': 'Ввести вручную',
  'scanner.result': 'Найден товар: {{product}}',
  'scanner.notFound': 'Товар не найден.',
  'scanner.tryAgain': 'Попробовать ещё раз',

  'confirm.discardChanges.title': 'Отменить изменения?',
  'confirm.discardChanges.description': 'Несохранённые данные будут потеряны.',
  'confirm.deleteProduct.title': 'Удалить товар?',
  'confirm.deleteProduct.description': 'Товар «{{product}}» будет удалён из списка.',
  'confirm.deleteStore.title': 'Удалить магазин?',
  'confirm.deleteStore.description': 'Активные товары будут перемещены в «Не распределено».',
  'confirm.deleteList.title': 'Удалить список?',
  'confirm.deleteList.description': 'Товары из списка будут удалены.',
  'confirm.deleteHistory.title': 'Удалить запись из истории?',
  'confirm.deleteHistory.description': 'Эту покупку можно будет восстановить через уведомление.',
  'confirm.completeList.title': 'Завершить покупку?',
  'confirm.completeList.description': 'Список появится в истории покупок.',
  'confirm.clearHistory.title': 'Очистить историю?',
  'confirm.clearHistory.description': 'Все завершённые покупки будут удалены.',
  'confirm.removeMember.title': 'Удалить участника?',
  'confirm.removeMember.description': '{{name}} потеряет доступ к списку.',

  'toast.productAdded': 'Товар добавлен',
  'toast.productUpdated': 'Товар изменён',
  'toast.productDeleted': 'Товар удалён',
  'toast.productRestored': 'Товар восстановлен',
  'toast.productPurchased': 'Отмечено как купленное',
  'toast.productReturned': 'Товар возвращён в покупки',
  'toast.productMoved': 'Перемещено в {{store}}',
  'toast.listCreated': 'Список создан',
  'toast.listOpened': 'Активный список открыт',
  'toast.listUpdated': 'Список изменён',
  'toast.listCompleted': 'Покупка завершена',
  'toast.storeAdded': 'Магазин добавлен',
  'toast.storeUpdated': 'Магазин изменён',
  'toast.storeDeleted': 'Магазин удалён',
  'toast.historyDeleted': 'Запись удалена',
  'toast.memberInvited': 'Приглашение отправлено',
  'toast.settingsSaved': 'Настройки сохранены',
  'toast.exportReady': 'Экспорт подготовлен',
  'toast.demoRestored': 'Демонстрационные данные восстановлены',

  'validation.required': 'Заполните это поле.',
  'validation.nameRequired': 'Введите название.',
  'validation.quantityPositive': 'Количество должно быть больше нуля.',
  'validation.priceNonNegative': 'Цена не может быть отрицательной.',
  'validation.emailInvalid': 'Введите корректный email.',
  'validation.urlInvalid': 'Введите корректную ссылку.',
  'validation.selectStore': 'Выберите магазин.',
  'validation.selectProduct': 'Выберите хотя бы один товар.',
  'validation.tooLong': 'Слишком длинное значение.',

  'error.loadFailed': 'Не удалось загрузить данные.',
  'error.saveFailed': 'Не удалось сохранить изменения.',
  'error.storageCorrupted': 'Локальные данные повреждены.',
  'error.storageRecovery': 'Восстановите демонстрационные данные, чтобы продолжить.',
  'error.actionFailed': 'Не удалось выполнить действие.',
  'error.notFound': 'Запрошенный экран не найден.',
  'error.permissionDenied': 'У вас нет прав для этого действия.',
  'error.unknown': 'Произошла неизвестная ошибка.',

  'mock.localData': 'Демонстрационные данные хранятся локально.',
  'mock.noStoreApis': 'Подключение к сервисам магазинов пока не используется.',
  'mock.featureComingSoon': 'Эта функция пока доступна только как демонстрация.',

  'demo.product.bananas': 'Бананы',
  'demo.product.milk': 'Молоко 2,5%',
  'demo.product.bread': 'Хлеб',
  'demo.product.eggs': 'Яйца',
  'demo.product.cheese': 'Сыр',
  'demo.product.water': 'Вода',
  'demo.product.napkins': 'Салфетки',
} as const

export type TranslationKey = keyof typeof ru
