import type { TranslationKey } from './ru'

export const uk = {
  'app.name': 'OneCart',
  'app.logoLabel': 'Логотип OneCart',

  'nav.home': 'Головна',
  'nav.stores': 'Магазини',
  'nav.add': 'Додати',
  'nav.history': 'Історія',
  'nav.profile': 'Профіль',
  'nav.mainLabel': 'Основна навігація',

  'common.back': 'Назад',
  'common.close': 'Закрити',
  'common.cancel': 'Скасувати',
  'common.save': 'Зберегти',
  'common.done': 'Готово',
  'common.continue': 'Продовжити',
  'common.start': 'Почати',
  'common.add': 'Додати',
  'common.create': 'Створити',
  'common.edit': 'Змінити',
  'common.delete': 'Видалити',
  'common.remove': 'Прибрати',
  'common.rename': 'Перейменувати',
  'common.open': 'Відкрити',
  'common.confirm': 'Підтвердити',
  'common.retry': 'Повторити',
  'common.undo': 'Скасувати',
  'common.search': 'Пошук',
  'common.clear': 'Очистити',
  'common.apply': 'Застосувати',
  'common.select': 'Вибрати',
  'common.selected': 'Вибрано: {{count}}',
  'common.more': 'Ще',
  'common.share': 'Поділитися',
  'common.invite': 'Запросити',
  'common.move': 'Перемістити',
  'common.pin': 'Закріпити',
  'common.unpin': 'Відкріпити',
  'common.yes': 'Так',
  'common.no': 'Ні',
  'common.optional': "Необов'язково",
  'common.required': "Обов'язково",
  'common.enabled': 'Увімкнено',
  'common.disabled': 'Вимкнено',
  'common.notSpecified': 'Не вказано',
  'common.notAvailable': 'Недоступно',
  'common.productsCount': 'Товарів: {{count}}',
  'common.purchasedProgress': 'Куплено: {{purchased}} із {{total}}',
  'common.approximate': 'Орієнтовно',
  'common.currencyUah': 'Гривня (₴)',

  'a11y.pageIndicator': 'Крок {{current}} із {{total}}',
  'a11y.skipToContent': 'Перейти до вмісту',
  'a11y.openNotifications': 'Відкрити сповіщення',
  'a11y.openProfile': 'Відкрити профіль',
  'a11y.openMoreMenu': 'Відкрити додаткове меню',
  'a11y.closeSheet': 'Закрити нижнє меню',
  'a11y.openStoreList': 'Відкрити список магазину {{store}}',
  'a11y.markPurchased': 'Позначити {{product}} як куплений товар',
  'a11y.markNotPurchased': 'Повернути {{product}} до списку покупок',
  'a11y.expandCategory': 'Розгорнути категорію {{category}}',
  'a11y.collapseCategory': 'Згорнути категорію {{category}}',
  'a11y.progress': 'Куплено {{purchased}} із {{total}} товарів',
  'a11y.decreaseQuantity': 'Зменшити кількість',
  'a11y.increaseQuantity': 'Збільшити кількість',

  'splash.title': 'OneCart',

  'onboarding.first.title': 'Усі покупки в одному місці',
  'onboarding.first.description':
    'Створюйте списки для будь-яких магазинів і керуйте ними з одного застосунку.',
  'onboarding.second.title': 'Купуйте разом',
  'onboarding.second.description':
    'Діліться списком із родиною та одразу бачте зміни.',
  'onboarding.third.title': 'Нічого не забудьте',
  'onboarding.third.description':
    'Додавайте товари вручну, голосом або з історії покупок.',
  'onboarding.continue': 'Продовжити',
  'onboarding.start': 'Почати',

  'home.greeting': 'Вітаємо',
  'home.title': 'Мої покупки',
  'home.generalList': 'Загальний список',
  'home.openGeneralList': 'Відкрити загальний список',
  'home.storeLists': 'Списки за магазинами',
  'home.frequentProducts': 'Часто купуєте',
  'home.chooseDestination': 'Виберіть список для товару',
  'home.addedToList': '{{product}} додано до {{list}}',
  'home.allPurchased': 'Усі товари куплено',
  'home.noActivePurchases': 'Активних покупок поки немає',

  'quickActions.title': 'Що додати?',
  'quickActions.product': 'Додати товар',
  'quickActions.list': 'Створити список',
  'quickActions.store': 'Додати магазин',
  'quickActions.voice': 'Додати товар голосом',

  'stores.title': 'Магазини',
  'stores.add': 'Додати магазин',
  'stores.openList': 'Відкрити список',
  'stores.status': 'Статус списку',
  'stores.status.active': 'Активний',
  'stores.status.completed': 'Завершений',
  'stores.status.empty': 'Порожній',
  'stores.menu.rename': 'Перейменувати',
  'stores.menu.changeLocation': 'Змінити місцезнаходження',
  'stores.menu.changeColor': 'Змінити колір',
  'stores.menu.pin': 'Закріпити',
  'stores.menu.unpin': 'Відкріпити',
  'stores.menu.openOfficialApp': 'Відкрити офіційний застосунок',
  'stores.menu.delete': 'Видалити з OneCart',
  'stores.externalAppUnavailable': 'Посилання на офіційний застосунок не додано.',
  'stores.customBadge': 'Власний магазин',
  'stores.location.notSpecified': 'Місцезнаходження не вказано',

  'storeCatalog.title': 'Каталог магазинів',
  'storeCatalog.searchLabel': 'Знайти магазин',
  'storeCatalog.searchPlaceholder': 'Назва магазину',
  'storeCatalog.popular': 'Популярні магазини',
  'storeCatalog.other': 'Інший магазин',
  'storeCatalog.configure': 'Налаштувати',
  'storeCatalog.addStandard': 'Додати магазин',
  'storeCatalog.setupTitle': 'Налаштування {{store}}',
  'storeCatalog.setupDescription': 'Укажіть філію, параметри списку та посилання мережі.',
  'storeCatalog.favoriteBranch': 'Улюблена філія або адреса',
  'storeCatalog.branchHint': 'Укажіть адресу або назву філії. Це необов’язково.',
  'storeCatalog.includeInGeneral': 'Додати до загального списку',
  'storeCatalog.includeInGeneralHint':
    'Створити активний список магазину та показувати його товари в загальному списку.',
  'storeCatalog.externalAppUrl': 'Посилання на сайт або каталог',
  'storeCatalog.externalAppUrlHint':
    'Використовується для дії «Відкрити офіційний застосунок».',
  'storeCatalog.noResults': 'Магазинів не знайдено',
  'storeCatalog.noResultsHint': 'Перевірте назву або додайте власний магазин.',
  'storeForm.createTitle': 'Новий магазин',
  'storeForm.editTitle': 'Змінити магазин',
  'storeForm.name': 'Назва',
  'storeForm.namePlaceholder': 'Наприклад, Магазин біля дому',
  'storeForm.color': 'Колір',
  'storeForm.icon': 'Іконка',
  'storeForm.city': 'Місто',
  'storeForm.cityPlaceholder': 'Оберіть або введіть місто',
  'storeForm.address': 'Адреса',
  'storeForm.addressPlaceholder': 'Вулиця, будинок або назва філії',
  'storeForm.useCurrentLocation': 'Використати моє місцезнаходження',
  'storeForm.locating': 'Визначаємо місцезнаходження…',
  'storeForm.locationReady': 'Координати збережено й буде показано разом з адресою.',
  'storeForm.locationUnsupported': 'Геолокація не підтримується на цьому пристрої.',
  'storeForm.locationDenied': 'Не вдалося отримати геолокацію. Перевірте дозвіл застосунку.',
  'storeForm.coordinates': 'Координати',
  'storeForm.branch': 'Філія',
  'storeForm.saveUrl': 'Зберегти посилання на застосунок',

  'lists.generalTitle': 'Загальний список покупок',
  'lists.unassigned': 'Не розподілено',
  'lists.distributed': 'Розподілено за магазинами',
  'lists.remaining': 'Залишилося купити',
  'lists.purchased': 'Куплено',
  'lists.addProduct': 'Додати товар',
  'lists.create': 'Створити список',
  'lists.createTitle': 'Новий список',
  'lists.activeExists': 'Для цього розділу вже є активний список. Його можна відкрити без створення дубля.',
  'lists.editTitle': 'Змінити список',
  'lists.name': 'Назва списку',
  'lists.store': 'Магазин',
  'lists.noStore': 'Без магазину',
  'lists.purchaseMode': 'Режим покупки',
  'lists.bulkDistribution': 'Розподілити товари',
  'lists.completePurchase': 'Завершити покупку',
  'lists.completeUnavailable': 'Спочатку позначте всі товари як куплені.',
  'lists.itemsRemaining': 'Залишилося: {{count}}',
  'lists.categoryCount': 'У категорії: {{count}}',
  'lists.expandCategory': 'Показати товари',
  'lists.collapseCategory': 'Сховати товари',
  'lists.sharedAccess': 'Спільний доступ',
  'lists.updatedAt': 'Оновлено {{date}}',
  'lists.addedBy': 'Додав {{name}}',

  'products.addTitle': 'Додати товар',
  'products.editTitle': 'Змінити товар',
  'products.detailsTitle': 'Картка товару',
  'products.name': 'Назва',
  'products.namePlaceholder': 'Що потрібно купити?',
  'products.quantity': 'Кількість',
  'products.unit': 'Одиниця вимірювання',
  'products.store': 'Магазин',
  'products.category': 'Категорія',
  'products.estimatedPrice': 'Орієнтовна ціна',
  'products.priceHint': 'Ціну вказано приблизно',
  'products.photo': 'Фото товару',
  'products.photoAlt': 'Фото товару {{product}}',
  'products.photoSource': 'Офіційне джерело: {{source}}',
  'products.note': 'Нотатка',
  'products.notePlaceholder': 'Наприклад, без цукру',
  'products.mode.manual': 'Вручну',
  'products.mode.voice': 'Голосом',
  'products.mode.scanner': 'Сканером',
  'products.suggestions': 'Підказки з історії',
  'products.markPurchased': 'Позначити як куплене',
  'products.markNotPurchased': 'Повернути до покупок',
  'products.changeQuantity': 'Змінити кількість',
  'products.changeStore': 'Змінити магазин',
  'products.addNote': 'Додати нотатку',
  'products.addToFrequent': 'Додати до часто купуваних',
  'products.removeFromFrequent': 'Прибрати з часто купуваних',
  'products.delete': 'Видалити товар',
  'products.addedAt': 'Додано {{date}}',
  'products.addedBy': 'Додав {{name}}',
  'products.purchasedAt': 'Куплено {{date}}',
  'products.swipeDelete': 'Проведіть ліворуч, щоб видалити',
  'products.swipePurchase': 'Проведіть праворуч, щоб позначити як куплене',

  'units.piece': 'шт',
  'units.kg': 'кг',
  'units.g': 'г',
  'units.l': 'л',
  'units.ml': 'мл',
  'units.pack': 'упаковка',

  'categories.produce': 'Овочі та фрукти',
  'categories.dairy': 'Молочні продукти',
  'categories.meat': "М'ясо",
  'categories.drinks': 'Напої',
  'categories.household': 'Побутові товари',
  'categories.other': 'Інше',

  'moveProduct.title': 'Перемістити товар',
  'moveProduct.currentStore': 'Поточний магазин',
  'moveProduct.destination': 'Куди перемістити',
  'moveProduct.unassigned': 'Не розподілено',
  'moveProduct.confirm': 'Перемістити',
  'moveProduct.sameStore': 'Виберіть інший магазин.',
  'moveProduct.success': 'Товар переміщено до {{store}}',

  'distribution.title': 'Розподіл товарів',
  'distribution.description': 'Позначте товари та виберіть магазин.',
  'distribution.selectAll': 'Вибрати все',
  'distribution.clearSelection': 'Скасувати вибір',
  'distribution.chooseStore': 'Виберіть магазин',
  'distribution.confirm': 'Розподілити',
  'distribution.success': 'Розподілено товарів: {{count}}',
  'distribution.dragHint': 'Товари також можна перетягувати між магазинами.',

  'history.title': 'Історія покупок',
  'history.purchasesTab': 'Покупки',
  'history.frequentTab': 'Часто купувані',
  'history.detailsTitle': 'Покупка',
  'history.total': 'Підсумкова сума',
  'history.date': 'Дата покупки',
  'history.members': 'Учасники',
  'history.repeatList': 'Повторити весь список',
  'history.addAgain': 'Додати знову',
  'history.deleteEntry': 'Видалити запис',
  'history.completedAt': 'Завершено {{date}}',
  'history.repeatDestination': 'Куди додати товари?',
  'history.repeatSuccess': 'Список додано знову',
  'history.entrySummary': '{{store}} · товарів: {{count}}',

  'sharing.title': 'Спільний доступ',
  'sharing.shareStore': 'Поділитися магазином',
  'sharing.shareGeneralList': 'Поділитися загальним списком',
  'sharing.shareFamily': 'Поділитися всіма списками родини',
  'sharing.participants': 'Учасники',
  'sharing.invite': 'Запросити учасника',
  'sharing.invitePlaceholder': "Ім'я або email",
  'sharing.accessRights': 'Права доступу',
  'sharing.owner': 'Власник',
  'sharing.editor': 'Редактор',
  'sharing.viewer': 'Лише перегляд',
  'sharing.status.active': 'Активний',
  'sharing.status.pending': 'Очікує на запрошення',
  'sharing.removeMember': 'Видалити учасника',
  'sharing.simulateChange': 'Імітувати зміну',
  'sharing.simulatedChange': '{{name}} додав товар',

  'notifications.title': 'Сповіщення',
  'notifications.unreadCount': 'Непрочитаних: {{count}}',
  'notifications.markAllRead': 'Позначити всі як прочитані',
  'notifications.settings': 'Налаштування сповіщень',
  'notifications.mode.all': 'Усі зміни',
  'notifications.mode.important': 'Лише важливі',
  'notifications.muteList': 'Вимкнути для списку',
  'notifications.productAdded.title': 'Новий товар',
  'notifications.productAdded.message': '{{actor}}: додано товар «{{product}}».',
  'notifications.productPurchased.title': 'Товар куплено',
  'notifications.productPurchased.message': '{{actor}}: товар «{{product}}» позначено купленим.',
  'notifications.listChanged.title': 'Список змінено',
  'notifications.listChanged.message': '{{actor}}: список «{{list}}» змінено.',
  'notifications.memberJoined.title': 'Новий учасник',
  'notifications.memberJoined.message': '{{member}} приєднався до списку.',
  'notifications.listCompleted.title': 'Список завершено',
  'notifications.listCompleted.message': 'Покупку в {{store}} завершено.',

  'profile.title': 'Профіль',
  'profile.name': "Ім'я",
  'profile.email': 'Email',
  'profile.family': 'Родина',
  'profile.family.members': 'Учасники',
  'profile.family.invitations': 'Запрошення',
  'profile.family.permissions': 'Права доступу',
  'profile.application': 'Застосунок',
  'profile.data': 'Дані',
  'profile.support': 'Підтримка',

  'settings.title': 'Налаштування',
  'settings.notifications': 'Сповіщення',
  'settings.language': 'Мова',
  'settings.language.ru': 'Русский',
  'settings.language.uk': 'Українська',
  'settings.currency': 'Валюта',
  'settings.theme': 'Тема',
  'settings.theme.light': 'Світла',
  'settings.theme.dark': 'Темна',
  'settings.theme.system': 'Системна',
  'settings.theme.systemDescription': 'Системна тема автоматично відповідає налаштуванням пристрою.',
  'settings.units': 'Одиниці вимірювання',
  'settings.defaultUnit': 'Одиниця за замовчуванням',
  'settings.sync': 'Синхронізація',
  'settings.sync.localOnly': 'Дані зберігаються лише на цьому пристрої.',
  'settings.backup': 'Резервна копія',
  'settings.backupDescription': 'Завантажити локальну JSON-копію даних',
  'settings.export': 'Експорт списків',
  'settings.exportDescription': 'Завантажити товари й списки у CSV',
  'settings.clearHistory': 'Очищення історії',
  'settings.help': 'Допомога',
  'settings.feedback': "Зворотний зв'язок",
  'settings.about': 'Про застосунок',
  'settings.aboutDescription': 'OneCart об’єднує списки покупок для різних магазинів.',
  'settings.version': 'Версія {{version}}',
  'settings.resetDemo': 'Відновити демонстраційні дані',

  'empty.lists.title': 'Списків поки немає',
  'empty.lists.description':
    'Створіть перший список і додайте товари, які потрібно купити.',
  'empty.lists.action': 'Створити список',
  'empty.products.title': 'Список порожній',
  'empty.products.description': 'Додайте перший товар вручну або голосом.',
  'empty.products.action': 'Додати товар',
  'empty.history.title': 'Покупок поки немає',
  'empty.history.description': 'Завершені списки з’являться тут.',
  'empty.stores.title': 'Магазинів поки немає',
  'empty.stores.description': 'Додайте магазин, щоб створити для нього список.',
  'empty.notifications.title': 'Нових сповіщень немає',
  'empty.notifications.description': 'Зміни у спільних списках з’являться тут.',
  'empty.search.title': 'Нічого не знайдено',
  'empty.search.description': 'Спробуйте змінити запит.',
  'empty.frequent.title': 'Часто купуваних товарів поки немає',
  'empty.frequent.description': 'Додавайте товари, і тут з’являться ваші звичні покупки.',

  'state.loading': 'Завантаження…',
  'state.loadingData': 'Завантажуємо ваші списки…',
  'state.saving': 'Зберігаємо…',
  'state.success': 'Готово',
  'state.offline.title': 'Немає підключення до інтернету',
  'state.offline.description': 'Офлайн. Зміни збережено на пристрої.',
  'state.error.title': 'Щось пішло не так',
  'state.error.description': 'Не вдалося завантажити дані. Спробуйте ще раз.',
  'state.disabledReason': 'Дія поки недоступна: {{reason}}',
  'state.unsavedChanges': 'Є незбережені зміни.',

  'voice.title': 'Додавання голосом',
  'voice.idle': 'Натисніть кнопку та назвіть товар.',
  'voice.start': 'Почати запис',
  'voice.stop': 'Зупинити запис',
  'voice.listening': 'Слухаю…',
  'voice.transcript': 'Розпізнаний текст',
  'voice.confirm': 'Додати цей товар',
  'voice.tryAgain': 'Записати ще раз',
  'voice.permissionDenied': 'Немає доступу до мікрофона.',
  'voice.permissionHint': 'Дозвольте доступ або додайте товар вручну.',
  'voice.mockNotice': 'У прототипі голосове введення працює як демонстрація.',
  'voice.simulate': 'Імітувати розпізнавання',

  'scanner.title': 'Сканер товару',
  'scanner.instruction': 'Розмістіть штрихкод у рамці.',
  'scanner.mockNotice': 'Розпізнавання штрихкоду поки працює як демонстрація.',
  'scanner.simulate': 'Імітувати результат',
  'scanner.manual': 'Ввести вручну',
  'scanner.result': 'Знайдено товар: {{product}}',
  'scanner.notFound': 'Товар не знайдено.',
  'scanner.tryAgain': 'Спробувати ще раз',

  'confirm.discardChanges.title': 'Скасувати зміни?',
  'confirm.discardChanges.description': 'Незбережені дані буде втрачено.',
  'confirm.deleteProduct.title': 'Видалити товар?',
  'confirm.deleteProduct.description': 'Товар «{{product}}» буде видалено зі списку.',
  'confirm.deleteStore.title': 'Видалити магазин?',
  'confirm.deleteStore.description': 'Активні товари буде переміщено до «Не розподілено».',
  'confirm.deleteList.title': 'Видалити список?',
  'confirm.deleteList.description': 'Товари зі списку буде видалено.',
  'confirm.deleteHistory.title': 'Видалити запис з історії?',
  'confirm.deleteHistory.description': 'Цю покупку можна буде відновити через сповіщення.',
  'confirm.completeList.title': 'Завершити покупку?',
  'confirm.completeList.description': 'Список з’явиться в історії покупок.',
  'confirm.clearHistory.title': 'Очистити історію?',
  'confirm.clearHistory.description': 'Усі завершені покупки буде видалено.',
  'confirm.removeMember.title': 'Видалити учасника?',
  'confirm.removeMember.description': '{{name}} втратить доступ до списку.',

  'toast.productAdded': 'Товар додано',
  'toast.productUpdated': 'Товар змінено',
  'toast.productDeleted': 'Товар видалено',
  'toast.productRestored': 'Товар відновлено',
  'toast.productPurchased': 'Позначено як куплене',
  'toast.productReturned': 'Товар повернуто до покупок',
  'toast.productMoved': 'Переміщено до {{store}}',
  'toast.listCreated': 'Список створено',
  'toast.listOpened': 'Активний список відкрито',
  'toast.listUpdated': 'Список змінено',
  'toast.listCompleted': 'Покупку завершено',
  'toast.storeAdded': 'Магазин додано',
  'toast.storeUpdated': 'Магазин змінено',
  'toast.storeDeleted': 'Магазин видалено',
  'toast.historyDeleted': 'Запис видалено',
  'toast.memberInvited': 'Запрошення надіслано',
  'toast.settingsSaved': 'Налаштування збережено',
  'toast.exportReady': 'Експорт підготовлено',
  'toast.demoRestored': 'Демонстраційні дані відновлено',

  'validation.required': 'Заповніть це поле.',
  'validation.nameRequired': 'Введіть назву.',
  'validation.quantityPositive': 'Кількість має бути більшою за нуль.',
  'validation.priceNonNegative': 'Ціна не може бути від’ємною.',
  'validation.emailInvalid': 'Введіть коректний email.',
  'validation.urlInvalid': 'Введіть коректне посилання.',
  'validation.selectStore': 'Виберіть магазин.',
  'validation.selectProduct': 'Виберіть хоча б один товар.',
  'validation.tooLong': 'Значення задовге.',

  'error.loadFailed': 'Не вдалося завантажити дані.',
  'error.saveFailed': 'Не вдалося зберегти зміни.',
  'error.storageCorrupted': 'Локальні дані пошкоджено.',
  'error.storageRecovery': 'Відновіть демонстраційні дані, щоб продовжити.',
  'error.actionFailed': 'Не вдалося виконати дію.',
  'error.notFound': 'Запитаний екран не знайдено.',
  'error.permissionDenied': 'У вас немає прав для цієї дії.',
  'error.unknown': 'Сталася невідома помилка.',

  'mock.localData': 'Демонстраційні дані зберігаються локально.',
  'mock.noStoreApis': 'Підключення до сервісів магазинів поки не використовується.',
  'mock.featureComingSoon': 'Ця функція поки доступна лише як демонстрація.',

  'demo.product.bananas': 'Банани',
  'demo.product.milk': 'Молоко 2,5%',
  'demo.product.bread': 'Хліб',
  'demo.product.eggs': 'Яйця',
  'demo.product.cheese': 'Сир',
  'demo.product.water': 'Вода',
  'demo.product.napkins': 'Серветки',
} as const satisfies Record<TranslationKey, string>
